Updated metadata + Screenshots
sugarlabs/help-activity pull request #5
Opened 2018-12-08 12:30 UTC by Gabbar8055

2018-12-09 16:55 UTC, vipulgupta2048 requested changes
Thanks for the pull request @Gabbar8055 
From what I am seeing, the help activity is being maintained here - https://github.com/godiard/help-activity
Please make a PR there.

2018-12-09 16:55 UTC, vipulgupta2048 commented on activity/activity.info
>  license = GPLv3
`GPLv3` will be `GPLv3+`

2018-12-10 01:05 UTC, quozl commented
Closing because @Gabbar8055 forgot to do so after opening https://github.com/godiard/help-activity/pull/103

2018-12-10 01:05 UTC, closed without merging

2018-12-10 16:49 UTC, vipulgupta2048 commented
Thanks @Quozl

On Mon 10 Dec, 2018, 6:35 AM James Cameron, <notifications@github.com>
wrote:

> Closed #5 <https://github.com/sugarlabs/help-activity/pull/5>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/sugarlabs/help-activity/pull/5#event-2014695629>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AVvtnuKuIbvpnNJED-wuMm1ZLM5Wp6Vfks5u3bM-gaJpZM4ZJnaC>
> .
>