help-activity
sugarlabs/help-activity pull request #9
Opened 2020-01-20 23:19 UTC by nwolisaemmanuel2

Update

2020-01-21 00:37 UTC, quozl requested changes
Thanks.  Good start, but I'm not sure English is your first language.

Also, please avoid editing files using GitHub, as we get multiple notifications and meaningless commit messages.  Please see our guide to [commit messages](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).

2020-01-21 00:37 UTC, quozl commented on README.md
> +Help is an activity which aims to provide users with easy access to documentation and manual.
No, _manuals_ is correct, as the aim is to link Help to multiple other manuals.

2020-01-21 00:37 UTC, quozl commented on README.md
> +Help can be accesed.
No, there should not be a full stop here; it is a line that introduces a list.

2020-01-21 00:37 UTC, quozl commented on README.md
> +### How to edit, Help and Contribute:
No, in this context "Help" is the name of the activity, so a comma is not correct.

2020-01-21 00:37 UTC, quozl commented on README.md
> +When contextual help( <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>h</kbd> ) is requested from within an sugar activity, the [helplink.json](helplink.json) file matches the bundle_id(the same as defined
This change is not correct.  The json file does link to a single page.

2020-01-21 00:37 UTC, quozl commented on README.md
> +###### More information to be found at
Change is unnecessary.

2020-03-01 23:06 UTC, chimosky commented
@nwolisaemmanuel2 do you plan on completing this?

2020-03-09 12:55 UTC, chimosky commented
Stale, closing.

2020-03-09 12:55 UTC, closed without merging